[package]
name = "eytzinger_sort"
version = "0.1.0"
authors = ["Maxim Zaks <maxim.zaks@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eytzinger = "1.0.1"
rand = "0.7"

[dev-dependencies]
